name: my-project
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas=2.3.2
  - numpy=2.3.3
  - python-dateutil=2.9.0
  - pytz=2025.2
  - six=1.17.0
  - tzdata=2025.2
  - pip
  - pip:
      - -r requirements.txt
